import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useMindmapsStore = defineStore('mindmaps', () => {
  // State: Mindmaps array
  const mindmaps = ref([]);

  // Add a new mindmap
  function addMindmap(mindmap) {
    mindmaps.value.push(mindmap);
  }

  // Remove a mindmap by ID
  function removeMindmap(id) {
    mindmaps.value = mindmaps.value.filter((mindmap) => mindmap.id !== id);
  }

  // Initialize with default mindmap if needed
  function initialize() {
    if (mindmaps.value.length === 0) {
        mindmaps.value.push({
            id: 1,
            title: `Mind Map 1`,
            nodes: {
              id: 1,
              label: 'My Hive',
              color: '#6BF58A',
              textColor: 'black',
              editing: false,
              borderShape: '',
              borderStyle: "solid",
              type: 'root',
              history: [],
              children: [
                {
                  id: 2,
                  label: 'Consumer App',
                  color: '#6BF58A',
                  textColor: 'black',
                  editing: false,
                  children: [{
                    id: 20,
                    label: 'Initial app setup',
                    color: '#6BF58A',
                    textColor: 'black',
                    editing: false,
                    children: [{
                      id: 21,
                      label: 'Onboarding',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 22,
                      label: ' Authentication',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [{
                        id: 222,
                        label: ' User can log in by providing their mobile number',
                        color: '#6BF58A',
                        textColor: 'black',
                        editing: false,
                        children: [],
                        type: 'story',
                        borderShape: '',
                        borderStyle: "solid",
                        history: [],
                      }, {
                        id: 223,
                        label: 'User can log in using email and password',
                        color: '#6BF58A',
                        textColor: 'black',
                        editing: false,
                        children: [],
                        type: 'story',
                        borderShape: '',
                        borderStyle: "solid",
                        history: [],
                      },],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 23,
                      label: ' Explore',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 24,
                      label: 'Bookings',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    },],
                    type: 'milestone',
                    borderShape: '',
                    borderStyle: "solid",
                    history: [],
                  },],
                  type: 'module',
                  borderShape: '',
                  borderStyle: "solid",
                  history: [],
                },
                {
                  id: 3,
                  label: 'Provider App',
                  color: '#6BF58A',
                  textColor: 'black',
                  editing: false,
                  children: [{
                    id: 31,
                    label: ' Initial app setup',
                    color: '#6BF58A',
                    textColor: 'black',
                    editing: false,
                    children: [{
                      id: 321,
                      label: ' Onboarding',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 322,
                      label: ' Authentication',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [{
                        id: 3222,
                        label: 'User can log in by providing their mobile number',
                        color: '#6BF58A',
                        textColor: 'black',
                        editing: false,
                        children: [],
                        type: 'story',
                        borderShape: '',
                        borderStyle: "solid",
                        history: [],
                      }, {
                        id: 3223,
                        label: 'User can log in using email and password',
                        color: '#6BF58A',
                        textColor: 'black',
                        editing: false,
                        children: [],
                        type: 'story',
                        borderShape: '',
                        borderStyle: "solid",
                        history: [],
                      },],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 323,
                      label: 'Explore',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 324,
                      label: 'Bookings',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    },],
                    type: 'milestone',
                    borderShape: '',
                    borderStyle: "solid",
                    history: [],
                  },],
                  type: 'module',
                  borderShape: '',
                  borderStyle: "solid",
                  history: [],
                },
                {
                  id: 4,
                  label: 'Company App',
                  color: '#6BF58A',
                  textColor: 'black',
                  editing: false,
                  children: [{
                    id: 41,
                    label: 'Initial app setup',
                    color: '#6BF58A',
                    textColor: 'black',
                    editing: false,
                    children: [{
                      id: 241,
                      label: 'Onboarding',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 242,
                      label: 'Authentication',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [{
                        id: 2242,
                        label: 'User can log in by providing their mobile number',
                        color: '#6BF58A',
                        textColor: 'black',
                        editing: false,
                        children: [],
                        type: 'story',
                        borderShape: '',
                        borderStyle: "solid",
                        history: [],
                      }, {
                        id: 2243,
                        label: 'User can log in using email and password',
                        color: '#6BF58A',
                        textColor: 'black',
                        editing: false,
                        children: [],
                        type: 'story',
                        borderShape: '',
                        borderStyle: "solid",
                        history: [],
                      },],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 423,
                      label: 'Explore',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    }, {
                      id: 424,
                      label: 'Bookings',
                      color: '#6BF58A',
                      textColor: 'black',
                      editing: false,
                      children: [],
                      type: 'feature',
                      borderShape: '',
                      borderStyle: "solid",
                      history: [],
                    },],
                    type: 'milestone',
                    borderShape: '',
                    borderStyle: "solid",
                    history: [],
                  },],
                  type: 'module',
                  borderShape: '',
                  borderStyle: "solid",
                  history: [],
                },
      
              ],
            }
          });
    }
  }

  return {
    mindmaps,
    addMindmap,
    removeMindmap,
    initialize,
  };
});
